#Config file for DeepLidar

#Data generation - the number of workers for dask session
num_hipergator_workers: 40
training_csvs:
  - NIWO

#LIDAR settings
min_density: 2
min_coverage: 30

#Keras
workers: 2
use_multiprocessing: False
max_queue_size: 20
num_GPUs: 1
save_image_path: /orange/ewhite/b.weinstein/retinanet/
save_snapshot_path: /orange/ewhite/b.weinstein/retinanet/
input_channels: 3

#Sliding Window Size and Ovelap
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
  zero_area: True

#Select sites
hand_annotation_site:
  - NIWO
  - SJER
  - TEAK
pretraining_site:
  - NIWO
  - SJER
  - TEAK
evaluation_site:
  - NIWO
  - SJER
  - TEAK
#Training
training_images: All
weights: /orange/ewhite/b.weinstein/retinanet/20190605_181458/resnet50_05.h5
imagenet_weights: True
batch_size: 20
epochs: 5
backbone: resnet50
shuffle_training: False
score_threshold: 0.15

#Evaluation
evaluation_images: 50
shuffle_evaluation: False
validation_percent: 5  #For hand annotation neon_MAP

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed. Higher allows more overlap.
nms_threshold: 0.1

#Data Paths
SJER:
  h5: /orange/ewhite/b.weinstein/training_h5s/blending/SJER/
  hand_annotations:
    RGB: /home/b.weinstein/DeepLidar/data/SJER/training/
    LIDAR: /home/b.weinstein/DeepLidar/data/SJER/training/
  training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/SJER/2018/
  training:
    RGB: /ufrc/ewhite/b.weinstein/NeonData/SJER/DP3.30010.001/2018/FullSite/D17/2018_SJER_3/L3/Camera/Mosaic/V01/
    LIDAR: /ufrc/ewhite/b.weinstein/NeonData/SJER/DP1.30003.001/2018/FullSite/D17/2018_SJER_3/L1/DiscreteLidar/ClassifiedPointCloud/
  evaluation:
    RGB: /home/b.weinstein/DeepLidar/data/SJER/plots/
    LIDAR: /home/b.weinstein/DeepLidar/data/SJER/plots/
TEAK:
  h5: /orange/ewhite/b.weinstein/training_h5s/blending/TEAK/
  training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/TEAK/2018/
  hand_annotations:
    RGB: /home/b.weinstein/DeepLidar/data/TEAK/training/
    LIDAR: /home/b.weinstein/DeepLidar/data/TEAK/training/
  training:
    RGB: /orange/ewhite/NeonData/TEAK/DP3.30010.001/2018/FullSite/D17/2018_TEAK_3/L3/Camera/Mosaic/V01/
    LIDAR: /orange/ewhite/NeonData/TEAK/DP1.30003.001/2018/FullSite/D17/2018_TEAK_3/L1/DiscreteLidar/ClassifiedPointCloud/
  evaluation:
    RGB: /home/b.weinstein/DeepLidar/data/TEAK/plots/
    LIDAR: /home/b.weinstein/DeepLidar/data/TEAK/plots/
NIWO:
  h5: /orange/ewhite/b.weinstein/training_h5s/blending/NIWO/
  training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/NIWO/2018/
  hand_annotations:
    RGB: /home/b.weinstein/DeepLidar/data/NIWO/training/
    LIDAR: /home/b.weinstein/DeepLidar/data/NIWO/training/
  training:
    RGB: /orange/ewhite/NeonData/NIWO/DP3.30010.001/2018/FullSite/D13/2018_NIWO_2/L3/Camera/Mosaic/V01/
    LIDAR: /orange/ewhite/NeonData/NIWO/DP1.30003.001/2018/FullSite/D13/2018_NIWO_2/L1/DiscreteLidar/ClassifiedPointCloud/
  evaluation:
    RGB: /home/b.weinstein/DeepLidar/data/NIWO/plots/
    LIDAR: /home/b.weinstein/DeepLidar/data/NIWO/plots/
